#
# 'make depend' uses makedepend to automatically generate dependencies 
#               (dependencies are added to end of Makefile)
# 'make'        build executable file 'mycc'
# 'make clean'  removes all .o and executable files
#

CC = g++
CFLAGS = -Wall -g -O2
INCLUDES = -I../eigen3
LFLAGS = -L../lib 

# List all the source files here
OBJS = math_test.o state.o

# Target 1
math_test: math_test.o state.o 
	$(CC) $(CFLAGS) $(INCLUDES) -o $@ $^ $(LFLAGS) $(LIBS)

# Pattern matching
# For targets of the form %.o (e.g. state.o) with the single
# dependency %.cpp (e.g. state.cpp). $< is %.cpp and $@ is
# %.o
#
%.o: %.cpp
	$(CC) $(CFLAGS) $(INCLUDES) -c $<  -o $@

.PHONY: depend clean

clean:
	-rm -f *.o *~ math_test

depend: $(OBJS:.o=.cpp)
	makedepend $(INCLUDES) $^
